version: 2.1
jobs:
  build:
    docker: 
      - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "npm installing" # run the `echo` command
      - run: npm install
      - run: CI=true npm run build # Declare an environmental variable
  test:
    docker: 
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - run: echo "testing stuff"
      - run: npm install
      - run: npm test
  hithere: # We can create test to run, for now just a dummy function
    docker:
      - image: cimg/node:14.10.1
    steps:
    - checkout
    - run: echo "helloooooooooo!"
workflows:
  version: 2
  build_test_lint:
    jobs: # The jobs, build and hithere, are going to run parallel
      - build
      - hithere
      - test: # the test job requires the hithere job to succeed
        requires:
          hithere
    
